name: Build ICU
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  Build:
    runs-on: macos-latest
    timeout-minutes: 120 # Keeps your builds from running too long
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: 'true'
    - name: Build
      run: scripts/build.sh
    - uses: actions/upload-artifact@v3
      with:
        name: product
        path: product
